### ISSUE TITLE
학습 데이터셋 라벨링 상태 점검 및 재라벨링

### ISSUE THREAD

**Issue by BBARRY-Lee** [BBARRY-Lee/Emotion-subtitle#7]
모델 성능 향상을 위해 학습 데이터셋 라벨링 상태 점검 및 재라벨링

**Comment by Bandi120424** [comment]
## 데이터셋
AI-Hub 감성대화말뭉치, 감성 분류를 위한 음성 데이터셋

### 1. 감성대화 말뭉치
Step 1. 감정_대분류 라벨을 4개의 label로 정리 
-  '당황', '상처': drop
-  '두려움'은 '불안'으로 재라벨링 

|   원 데이터 감정_대분류 라벨 |  정리 후 라벨 | 
|---|---|
|   분노, 불안, 기쁨, 두려움, 슬픔, 당황 상처 | 분노, 불안, 기쁨, 슬픔 |


Step 2. 감정_소분류 라벨을 고려하여 재라벨링

|   감정 소분류 |  원본 라벨링 | 재라벨링   | 문장갯수 |
|---|---|---|---|
|   안달하는 | 분노  |  불안   | 1746 |
|  좌절한, 방어적인 | 분노   | 슬픔   | 3356 | 
|  환멸을 느끼는 | 슬픔  |  분노  |  1768 |
|  회의적인 | 불안  |  슬픔  |  1720 |
|  취약한 | 불안|  슬픔  |  1728 |

Step 3.  형태소 분석 
- '화나다' 와 같이 감정을 직접적으로 대변하는 단어를 고려하여 데이터 재라벨링 
- soylemma, Open Korean Text (okt) 활용 

### 2. 감성 분류를 위한 음성 데이터셋
Step 1. 감정 라벨 4개의 label로 정리 
- 1-5번 감정세기 & 상황을 고려하여 지배적인 감정으로 해당 문장을 라벨링
- disgust를 angry로 라벨링 

Step 2. 발화문 길이가 10이하인 문장 제거 

Step 3. 형태소 분석

---

데이터 병합 후, 테스트 데이터의 문장 길이를 고려하여, 길이가 70을 초과하는 문장 제거
