### ISSUE TITLE
Muti-modal 감정 분류 모델 구현

### ISSUE THREAD

**Issue by BBARRY-Lee** [BBARRY-Lee/Emotion-subtitle#8]
text와 audio 데이터를 활용한 Muti-modal 감정 분류 모델 구현

**Comment by Bandi120424** [comment]
## 음성+텍스트 기반 감정 분류 모델 

1. pre-trained language model + CNN
- best accuracy: 78%

2. KoBERT + ResNet
- best accuracy: 60%
